### PR TITLE
Parts of the elevator structure

### PR DESCRIPTION
**Pull request by simeonackermann**
First pull request to add the parts of elevator structures.

Two open questions:
- shall I add possible properties of the parts (like width, height etc.) ? 
- do you need the paragraph of specification of each part?

### CODE REVIEW

**Comment by simeonackermann** [comment]
concerns #10

**Comment by simeonackermann** [comment]
I tried a better structure with properties and sources for each part in a table:

| Part | Features / Properties | Source |
| --- | --- | --- |
| Control panel | max./min. height above floor | DIN 81-20, 5.12.1 and <br>DIN 81-70, 5.4.2.2 |
| Position display | lighted | DIN 81-70, 5.4.2.4 |
| Well (Elevator shaft) |  | DIN 81-20, 5.2 |
| . Walls | width, depth | DIN 81-20, 5.2.5.2 |
| . . Guide rails |  | DIN 81-20, 5.7 |
| . Ceiling (headroom) |  |  |
| . Floor (pit) |  |  |
| . Buffer |  | DIN 81-20, 5.8 |
| . Lighting, emergency lighting |  | DIN 81-20, 5.2.1.4 |
| . Doors | min. clear open width | DIN 81-20, 5.3 |
| . . Protection device | e.g. light barries | DIN 81-20, 5.3.6 |
| . Car (cabine) | max. load control (DIN 81-20, 5.12.1.2) | DIN 81-20, 5.4 |
| . . Walls | width, depth, height |  |
| . . Ceiling |  |  |
| . . Doors | min. clear open width | DIN 81-20, 5.3 |
| . . . Protection device | e.g. light barries | DIN 81-20, 5.3.6 |
| . . Lighting, emergency lighting | min. luminosity | DIN 81-20, 5.4.10 |
| . . Control panel | max./min. height above floor | DIN 81-20, 5.12.1 and <br>DIN 81-20, table 4 |
| . . . Buttons | each level, close/open door,  symbols, min. size, relief | DIN 81-20, 5.12.1.1.2, and<br> DIN 81-70, 5.4 |
| . . . . Emergency call | bell symbol | DIN 81-20, 5.12.3 |
| . . Position display | lighted, max./min. height above floor | DIN 81-20, 5.12.1.1.3 |
| . . Ventilation |  | DIN 81-20, 5.4.9 |

**Comment by simeonackermann** [comment]
Do you think this visualization is more suitable?

**Comment by k00ni** [comment]
Looks great. I guess, i will merge it next week. Thanks!

**Pull request merged**
